### PR TITLE
Better path handling

### PR DESCRIPTION
**Pull request by jankeromnes**
It looks like `p.join(documentRoot, templatePath)` could be improved, so I replaced `var p = require('path')` with a custom closure.

@espadrine please have a look.

### CODE REVIEW

**Comment by jankeromnes** [comment]
Hm, `make test` fails with a `"close"` instead of a `"keep-alive"`. Does my pull request actually break something?

**Comment by espadrine** [comment]
Monkey-patching `path` is not the correct modification. This is an issue in the `staticUnit` part of the stack.

Sample code:

```js
var protectedPath = function(p) {
  return path.relative(documentRoot, p).replace(/^(..\/)+/, '');
};
```

**Comment by jankeromnes** [comment]
I'm actually not monkey-patching but completely replacing `path`, because several places in the code call `p.join`, but I think something else is expected:

https://github.com/espadrine/sc/blob/master/lib/camp.js#L463
https://github.com/espadrine/sc/blob/master/lib/camp.js#L469
https://github.com/espadrine/sc/blob/master/lib/camp.js#L580

**Comment by espadrine** [comment]
> I'm actually not monkey-patching but completely replacing path

That's what monkey-patching means. If it was written with node's `path` in mind, that shouldn't change. The `RouteUnit` part of the stack currently works as intended, for instance.

**Comment by jankeromnes** [comment]
I don't think that `RouteUnit`'s template paths should work like [line 580](https://github.com/espadrine/sc/blob/master/lib/camp.js#L580) makes them work.

**Comment by espadrine** [comment]
I understand that what you want is to make a server behave like a contained git repository with no outside knowledge. That is a fair argument. However, it is like saying that the standard C library ought not to let a program deal with paths outside of the program's directory. Yet programming would be painful if Unix did not allow to access RC files, say vimrc & cie.

I hope you understand my perspective. I still believe that allowing any path for routes, which are meant to execute templates, is ok.

**Pull request closed without merging**
